version: '3.3'
services:
  db:
    container_name: spring_maria_db
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=spring_test
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3306
